server:
  port: 9090
  servlet:
    context-path: /es-dre

#spring相关
spring:
  application:
    name: es-dre-provider
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
  #jpa配置
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true
    hibernate:
      use-new-id-generator-mappings: false
#      ddl-auto: update

#数据源配置
dre:
  datasource:
    url: jdbc:mysql://localhost:3306/es_dre_db?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

#RestTemplate配置
remote:
  maxTotalConnect: 200 #连接池的最大连接数
  maxConnectPerRoute: 100 #单个主机的最大连接数
  connectTimeout: 10000 #连接超时
  readTimeout: 30000 #读取超时

#es相关
es:
#  url: http://localhost:9200 #es服务地址
  url: http://10.14.69.82:9200 #es服务地址
#  url: http://es-cn-0pp0xgmc90002c8jz.public.elasticsearch.aliyuncs.com:9200 #es服务地址
  userName: elastic #es用户名
  password: 20181203Wdd #es密码
  doc:
    pipelineName: hkvs #管道名称
    indexName: hkvs #索引名称
    indexType: doc #索引类型